# main.py
# (C) Martin Alebachew, 2023
# Nestor — RavKav Traffic Analysis Reports [ PROJECT ITHACA ]

from docx import Document
from docx.shared import Cm
from datetime import datetime

version = "0.1"


def intro():
    print(f"""                                      
         ,--.                                                  
       ,--.'|                        ___                       
   ,--,:  : |                      ,--.'|_                     
,`--.'`|  ' :                      |  | :,'   ,---.    __  ,-. 
|   :  :  | |            .--.--.   :  : ' :  '   ,'\ ,' ,'/ /| 
:   |   \ | :   ,---.   /  /    '.;__,'  /  /   /   |'  | |' | 
|   : '  '; |  /     \ |  :  /`./|  |   |  .   ; ,. :|  |   ,' 
'   ' ;.    ; /    /  ||  :  ;_  :__,'| :  '   | |: :'  :  /   
|   | | \   |.    ' / | \  \    `. '  : |__'   | .; :|  | '    
'   : |  ; .''   ;   /|  `----.   \|  | '.'|   :    |;  : |    
|   | '`--'  '   |  / | /  /`--'  /;  :    ;\   \  / |  , ;    
'   : |      |   :    |'--'.     / |  ,   /  `----'   ---'     
;   |.'       \   \  /   `--'---'   ---`-'                     
'---'          `----'                                          

      RavKav Traffic Analysis Reports | Project Ithaca
               (C) Martin Alebachew, 2023
                       Version {version}
""")


class Template:
    class Request:
        width = [Cm(size) for size in (1.25, 1.25, 11.6, 0.8, 0.8)]
        headerText = ('NO', 'DIR', 'Data', 'SW1', 'SW2')

    class Response:
        width = [Cm(size) for size in (1.25, 1.25, 1, 1, 0.8, 0.8, 0.8, 8, 0.8)]
        headerText = ('NO', 'DIR', 'CLA', 'INS', 'P1', 'P2', 'Lc', 'Data', 'Le')


class Report:
    def __init__(self, date, title, author):
        # Document constants
        self.INITIAL_ROWS = 1
        self.COLUMNS = 9

        # Create a document
        self.document = Document()
        self.__addInfo(date, title, author)
        self.__lastUsedRow = 0  # Non zero-based
        self.__lastEmptyRow = self.INITIAL_ROWS  # Non zero-based

        # Add table
        self.table = self.document.add_table(rows=self.INITIAL_ROWS, cols=self.COLUMNS, style="Table Grid")
        self.table.allow_autofit = False
        self.__setInitialWidths()

    def __setInitialWidths(self):
        cells = self.table.rows[0].cells
        for i, cell in enumerate(cells):
            cell.width = Template.Response.width[i]

    def __getNextRow(self):
        # TODO: improve efficiency :)
        self.__lastUsedRow += 1

        if self.__lastUsedRow > self.__lastEmptyRow:
            self.__lastEmptyRow += 1
            return self.table.add_row()

        return self.table.rows[self.__lastUsedRow - 1]  # Convert to zero-based

    def __addInfo(self, date, title, author):
        self.document.add_heading('RavKav Traffic Analysis Report', 1)
        self.document.add_paragraph(
            f'{title}, recorded by {author}\n'
            f'Generated by Nestor {version} on {date}')

    def addRecord(self, direction, packet):
        if direction == 'in' or direction == '>':
            self.__addRecordIn(packet)
        elif direction == 'out' or direction == '<':
            self.__addRecordOut(packet)
        else:
            raise ValueError

    def __addRecordOut(self, packet):
        # Add header row
        headerCells = self.__getNextRow().cells

        for i, cell in enumerate(headerCells):
            cell.text = Template.Response.headerText[i]

        # Add data row
        dataCells = self.__getNextRow().cells
        # TODO: specify direction

        # Add notes row
        notes = self.__addNotesRow()

    def __addNotesRow(self):
        notesCells = self.__getNextRow().cells
        firstCell = notesCells[0]
        lastCell = notesCells[self.COLUMNS - 1]  # Convert to zero-based

        firstCell.merge(lastCell)  # Merge whole row by diagonal cells
        firstCell.text = "Notes: ..."

    def save(self, filepath):
        self.document.save(filepath)


def main():
    intro()
    report = Report(datetime.now().strftime("%B %d, %Y at %H:%M:%S"), "Charging RavKav", "Martin Alebachew")
    report.addRecord("<", "boom!")
    report.save("/Users/martin/Documents/Coding/Ithaca/Nestor/generated_doc.docx")


if __name__ == '__main__':
    main()
